Repository env0/env0-client-integrations, pull requests merged in 2020-08, with the labels that each got.

#32 Chore: update readme
  node/.gitignore
  node/README.md
  node/bin/cli.js
  node/index.js
  node/package.json
Labels: chore, pending final review

#36 Chore: re-arrange folders and files
  node/bin/cli.js
  node/package.json
  node/src/commands/approve.js
  node/src/commands/cancel.js
  node/src/commands/deploy.js
  node/src/commands/destroy.js
  node/src/commands/help.js
  node/src/commands/run-command.js
  node/src/config/arguments.js
  node/src/config/commands.js
  node/src/config/constants.js
  node/src/env0-deploy-cli.js
  node/src/env0-deploy-flow.js
  node/src/lib/api-client.js
  node/src/lib/config-manager.js
  node/src/lib/deploy-utils.js
  node/src/lib/set-deployment-approval-status.js
  node/src/main.js
  node/tests/commands/run-command.spec.js
  node/tests/env0-deploy-flow.spec.js
  node/tests/lib/api-client.spec.js
  node/tests/lib/config-manager.spec.js
  node/tests/lib/deploy-utils.spec.js
  node/tests/main.spec.js
Labels: chore, pending final review

#37 Feat: add configure command
  node/README.md
  node/package.json
  node/src/commands/configure.js
  node/src/config/commands.js
  node/src/main.js
  node/tests/main.spec.js
  node/yarn.lock
Labels: feature, reviewed - awaiting author

#38 Chore: add logger and hide secrets
  node/package.json
  node/src/commands/deploy.js
  node/src/commands/run-command.js
  node/src/config/arguments.js
  node/src/lib/config-manager.js
  node/src/lib/deploy-utils.js
  node/src/lib/logger.js
  node/src/main.js
  node/tests/lib/logger.spec.js
  node/tests/main.spec.js
  node/yarn.lock
Labels: chore, pending final review

#39 Fix: final qa rejects
  node/README.md
  node/jest.config.js
  node/package.json
  node/src/commands/cancel.js
  node/src/commands/configure.js
  node/src/commands/deploy.js
  node/src/commands/destroy.js
  node/src/commands/help.js
  node/src/commands/run-command.js
  node/src/config/arguments.js
  node/src/config/constants.js
  node/src/lib/deploy-utils.js
  node/src/lib/genetal-utils.js
  node/src/lib/set-deployment-approval-status.js
  node/src/main.js
  node/tests/commands/configure.spec.js
  node/tests/commands/deploy.spec.js
  node/tests/commands/destroy.spec.js
  node/tests/commands/run-command.spec.js
  node/tests/lib/deploy-utils.spec.js
  node/yarn.lock
Labels: fix, pending final review

#42 Feat: add partial apply support
  node/src/commands/deploy.js
  node/src/config/arguments.js
  node/src/config/commands.js
  node/src/config/constants.js
  node/src/lib/deploy-utils.js
  node/tests/commands/deploy.spec.js
  node/tests/commands/destroy.spec.js
  node/tests/lib/deploy-utils.spec.js
Labels: feature, pending final review

#44 chore: upgraded the help
  node/src/commands/help.js
  node/src/config/arguments.js
  node/src/config/commands.js
Labels: bug, chore, documentation, fix, pending final review

#46 Fix: passing command options
  node/src/config/arguments.js
  node/src/main.js
  node/tests/main.spec.js
Labels: bug, fix

#48 Chore: add targets argument to README
  node/README.md
Labels: chore

#50 Fix: assert blueprint id for initial deployment
  node/src/commands/deploy.js
  node/tests/commands/deploy.spec.js
Labels: fix

#51 Chore: bump version to 1.0.4
  node/package.json
Labels: chore

#52 Fix: use configurationChanges field on deploy
  node/src/commands/deploy.js
  node/src/commands/destroy.js
  node/src/lib/deploy-utils.js
  node/src/lib/general-utils.js
  node/src/lib/genetal-utils.js
  node/tests/commands/deploy.spec.js
  node/tests/lib/deploy-utils.spec.js
  node/tests/lib/general-utils.spec.js
Labels: fix, pending final review

#53 Add workspace name parameter
  node/README.md
  node/src/commands/deploy.js
  node/src/config/arguments.js
  node/src/config/constants.js
  node/src/lib/deploy-utils.js
  node/tests/commands/deploy.spec.js
Labels: feature, pending final review

#54 Chore: add badges to readme
  node/README.md
Labels: chore, pending final review

#55 Feat: queued deployments
  node/src/commands/deploy.js
  node/src/commands/destroy.js
  node/src/lib/deploy-utils.js
  node/src/lib/set-deployment-approval-status.js
  node/tests/commands/deploy.spec.js
  node/tests/commands/destroy.spec.js
  node/tests/lib/deploy-utils.spec.js
Labels: feature, pending final review

#57 Chore: bump version 1.0.7
  node/package.json
Labels: chore
