Repository env0/env0-client-integrations, pull requests merged in 2020-09, with the labels that each got.

#58 Feat: add update notifier
  node/jest.config.js
  node/package.json
  node/src/main.js
  node/tests/main.spec.js
  node/yarn.lock
Labels: feature, pending final review

#59 Fix: add missing scope in configuration changes
  node/src/commands/deploy.js
  node/tests/commands/deploy.spec.js
Labels: fix, pending final review

#63 Fix: initial deployment wrong arguments
  node/src/lib/deploy-utils.js
  node/tests/lib/deploy-utils.spec.js
Labels: fix, pending final review

#62 Chore: yargs-parser security vulenrability
  node/package.json
  node/yarn.lock
Labels: chore, pending final review

#64 Chore: bump version 1.0.9
  node/package.json
Labels: chore

#66 Fix: support requires approval parameter in create api
  node/src/lib/deploy-utils.js
  node/tests/lib/deploy-utils.spec.js
Labels: fix, pending final review

#65 Fix: Persist configuration only in env0 configure
  node/src/commands/run-command.js
  node/tests/commands/run-command.spec.js
Labels: fix, pending final review

#67 Feat: Make env0 configure also non-interactive
  node/README.md
  node/src/commands/configure.js
  node/src/commands/help.js
  node/src/config/arguments.js
  node/src/config/commands.js
  node/src/main.js
  node/tests/commands/configure.spec.js
  node/tests/main.spec.js
Labels: feature, pending final review

#68 Fix: Most of the commands fail do to arguments not being resolved correctly
  node/src/main.js
  node/tests/commands/run-command.spec.js
  node/tests/main.spec.js
Labels: fix, pending final review

#69 Chore: Bump version to 1.0.10
  node/package.json
Labels: chore

#70 Fix: log errors properly based on axios response
  node/src/main.js
  node/tests/main.spec.js
Labels: fix, pending final review

#71 Fix: show better error messages #2
  node/src/main.js
  node/tests/main.spec.js
Labels: fix
