Repository env0/env0-client-integrations, pull requests merged in 2022-03, with the labels that each got.

#103 feat: adding support for Terraform Variables
  node/README.md
  node/npm-shrinkwrap.json
  node/src/commands/deploy.js
  node/src/commands/run-command.js
  node/src/config/arguments.js
  node/src/config/commands.js
  node/src/config/constants.js
  node/src/main.js
  node/tests/commands/deploy.spec.js
  node/tests/main.spec.js
  node/yarn.lock
Labels: enhancement, pending final review, feature

#105 chore: bump version to 1.0.16
  node/package.json
Labels: chore

#104 feature expose skip state refresh on plan phase to our CLI
  node/README.md
  node/package.json
  node/src/commands/deploy.js
  node/src/commands/destroy.js
  node/src/config/arguments.js
  node/src/config/commands.js
  node/src/config/constants.js
  node/src/lib/deploy-utils.js
  node/tests/commands/destroy.spec.js
  node/tests/lib/deploy-utils.spec.js
Labels: pending final review, feature

#107 added publish Github Action
  .github/workflows/auto_assign.yml
  .github/workflows/pr-auto-assign.yml
  .github/workflows/publish-npm.yml
  README.md
  node/README.md
Labels: pending final review, chore, reviewed - awaiting author
