Repository env0/env0-client-integrations, pull requests merged in 2022-09, with the labels that each got.

#112 Obtain JWT on client init
  node/src/lib/api-client.js
  node/tests/lib/api-client.spec.js
Labels: chore

#117 Revert: Obtain JWT on client init
  node/npm-shrinkwrap.json
  node/package.json
  node/src/lib/api-client.js
  node/tests/lib/api-client.spec.js
Labels: pending final review

#118 Chore: use node 14
  .github/workflows/ci.yml
  node/npm-shrinkwrap.json
  node/package.json
Labels: pending final review, chore

#120 Prepare release v1.0.21
  .github/pr-labeler.yml
  .github/release.yml
  node/npm-shrinkwrap.json
  node/package.json
Labels: prepare-release
